export const ZH_EN_REPLACEMENTS: Array<[string, string]> = [
  ['IDC 服务器担保交易', 'IDC Server Escrow'],
  ['首页', 'Home'],
  ['交易市场', 'Marketplace'],
  ['求购市场', 'Wanted'],
  ['议价中心', 'Bargain Center'],
  ['担保流程', 'Escrow Flow'],
  ['买家中心', 'Buyer Center'],
  ['卖家中心', 'Seller Center'],
  ['管理后台', 'Admin Console'],
  ['运营看板', 'Ops Dashboard'],
  ['用户管理', 'User Management'],
  ['商品审核', 'Product Review'],
  ['订单核验', 'Order Verification'],
  ['议价管理', 'Bargain Management'],
  ['寄售审核', 'Consignment Review'],
  ['支付监控', 'Payment Monitoring'],
  ['财务报表', 'Finance Overview'],
  ['支付对账', 'Payment Reconciliation'],
  ['结算放款', 'Settlement Release'],
  ['退款审核', 'Refund Review'],
  ['纠纷仲裁', 'Dispute Arbitration'],
  ['提现审核', 'Withdrawal Review'],
  ['风控策略', 'Risk Policy'],
  ['登录安全', 'Login Security'],
  ['规则协议', 'Policies & Rules'],
  ['开放接口监控', 'Open API Monitor'],
  ['通知管理', 'Notice Management'],
  ['内容运营', 'Content Operations'],
  ['操作日志', 'Audit Logs'],
  ['登录', 'Login'],
  ['注册', 'Sign Up'],
  ['退出登录', 'Logout'],
  ['退出', 'Logout'],
  ['刷新列表', 'Refresh List'],
  ['刷新中...', 'Refreshing...'],
  ['发送中...', 'Sending...'],
  ['发送通知', 'Send Notice'],
  ['发送区', 'Send Panel'],
  ['筛选区', 'Filters'],
  ['详情操作区', 'Detail Actions'],
  ['表格区', 'Table Section'],
  ['通知记录', 'Notice Records'],
  ['通知内容', 'Notice Content'],
  ['通知类型', 'Notice Type'],
  ['通知渠道', 'Channels'],
  ['状态筛选', 'Status Filter'],
  ['关键词', 'Keyword'],
  ['发送时间', 'Sent At'],
  ['目标用户', 'Target User'],
  ['通知', 'Notice'],
  ['类型', 'Type'],
  ['状态', 'Status'],
  ['操作', 'Action'],
  ['查看', 'View'],
  ['查看中', 'Viewing'],
  ['加载中...', 'Loading...'],
  ['暂无', 'No Data'],
  ['无内容', 'No Content'],
  ['广播记录', 'Broadcast'],
  ['站内通知', 'Site Notice'],
  ['邮件通知', 'Email'],
  ['微信模板', 'Wechat Template'],
  ['支付中心', 'Payment Center'],
  ['支付执行区', 'Payment Actions'],
  ['托管金额', 'Escrow Amount'],
  ['订单状态', 'Order Status'],
  ['交易模式', 'Trade Mode'],
  ['支付渠道', 'Payment Channel'],
  ['创建订单', 'Create Order'],
  ['发起支付', 'Initiate Payment'],
  ['平台托管', 'Escrow'],
  ['核验交付', 'Verification & Delivery'],
  ['结算放款', 'Settlement'],
  ['刷新支付状态', 'Refresh Payment Status'],
  ['模拟支付成功', 'Mock Success'],
  ['返回订单中心', 'Back to Orders'],
  ['打开独立支付页', 'Open Payment Page'],
  ['支付状态回执', 'Payment Status'],
  ['支付意图', 'Payment Intent'],
  ['交易号', 'Trade No'],
  ['支付时间', 'Paid At'],
  ['下一步', 'Next Action'],
  ['未支付', 'Unpaid'],
  ['已支付', 'Paid'],
  ['已退款', 'Refunded'],
  ['失败', 'Failed'],
  ['已关闭', 'Closed'],
  ['待支付', 'Pending Payment'],
  ['待交付', 'Waiting Delivery'],
  ['平台核验中', 'Platform Verifying'],
  ['买家验机中', 'Buyer Checking'],
  ['待结算', 'Pending Settlement'],
  ['已完成', 'Completed'],
  ['退款中', 'Refunding'],
  ['纠纷中', 'Disputing'],
  ['已取消', 'Canceled'],
  ['担保支付', 'Escrow Payment'],
  ['全程留痕', 'Traceability'],
  ['风险可控', 'Risk Controlled'],
  ['平台保障', 'Platform Guarantees'],
  ['交易流程', 'Trade Flow'],
  ['热门检索', 'Hot Filters'],
  ['热门类型', 'Popular Types'],
  ['热门地区', 'Popular Regions'],
  ['热门线路', 'Popular Routes'],
  ['帮助中心', 'Help Center'],
  ['常见问题', 'FAQ'],
  ['公告中心', 'Notice Center'],
  ['认证中心', 'Verification Center'],
  ['钱包与结算', 'Wallet & Settlement'],
  ['我的订单', 'My Orders'],
  ['我的求购', 'My Wanted'],
  ['我的议价', 'My Bargains'],
  ['浏览历史', 'History'],
  ['价格提醒', 'Price Alerts'],
  ['售后工单', 'Support Tickets'],
  ['卖家看板', 'Seller Dashboard'],
  ['店铺资料', 'Store Profile'],
  ['开放接口', 'Open API'],
  ['发布/管理商品', 'Product Management'],
  ['寄售申请', 'Consignment Application'],
  ['履约交付', 'Fulfillment'],
  ['议价会话', 'Bargain Sessions'],
  ['平台推荐', 'Featured'],
  ['在售市场', 'On-sale Market'],
  ['最新上架', 'Latest Listings'],
  ['担保交易', 'Escrow Trade'],
  ['平台寄售', 'Platform Consignment'],
  ['未启用寄售', 'Consignment Off'],
  ['寄售待审核', 'Consignment Pending'],
  ['寄售已通过', 'Consignment Approved'],
  ['寄售已驳回', 'Consignment Rejected'],
  ['寄售已撤销', 'Consignment Canceled'],
  ['风控', 'Risk'],
  ['风险', 'Risk'],
  ['风险标签', 'Risk Tags'],
  ['审核状态', 'Review Status'],
  ['审核备注', 'Review Notes'],
  ['审核时间', 'Reviewed At'],
  ['审核人', 'Reviewer'],
  ['卖家信誉', 'Seller Reputation'],
  ['成交次数', 'Trade Count'],
  ['纠纷率', 'Dispute Rate'],
  ['好评率', 'Positive Rate'],
  ['平均交付时间', 'Avg Delivery Time'],
  ['实名认证', 'Identity Verification'],
  ['交易资质', 'Trading Qualification'],
  ['通过', 'Approved'],
  ['驳回', 'Rejected'],
  ['待审核', 'Pending Review'],
  ['启用', 'Enabled'],
  ['禁用', 'Disabled'],
  ['成功', 'Success'],
  ['处理中', 'Processing'],
  ['删除', 'Delete'],
  ['编辑', 'Edit'],
  ['保存', 'Save'],
  ['提交', 'Submit'],
  ['取消', 'Cancel'],
  ['确认', 'Confirm'],
  ['搜索', 'Search'],
  ['清空', 'Clear'],
  ['全部', 'All'],
  ['返回', 'Back'],
  ['查看更多', 'View More'],
  ['暂无数据', 'No Data'],
  ['系统通知', 'System Notice'],
  ['消息中心', 'Messages'],
  ['公告', 'Announcements'],
  ['用户登录', 'User Login'],
  ['用户注册', 'User Registration'],
  ['邮箱地址', 'Email'],
  ['登录密码', 'Password'],
  ['忘记密码', 'Forgot Password'],
  ['邮箱验证', 'Verify Email'],
  ['登录并进入平台', 'Sign In'],
  ['注册并进入平台', 'Create Account'],
  ['登录中...', 'Signing In...'],
  ['注册中...', 'Signing Up...']
];

export function translateZhToEnText(input: string) {
  if (!input) return input;
  let output = input;
  for (const [zh, en] of ZH_EN_REPLACEMENTS) {
    if (output.includes(zh)) {
      output = output.split(zh).join(en);
    }
  }

  output = output
    .replace(/步骤\s*(\d+)/g, 'Step $1')
    .replace(/卖家\s*Lv\.(\d+)/g, 'Seller Lv.$1')
    .replace(/记录\s*(\d+)\s*条/g, '$1 records')
    .replace(/近\s*(\d+)\s*天/g, 'Last $1 days')
    .replace(/第\s*(\d+)\s*页/g, 'Page $1');

  return output;
}
